# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Coreocr < Formula
  desc "macOS CLI tool and Swift library for performing OCR using Vision"
  homepage "https://github.com/LESIM-Co-Ltd/CoreOCR"
  url "https://github.com/LESIM-Co-Ltd/CoreOCR/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "f3c0a99e85f0e62693c59b68ce290e11b2e991d0650a7997d0bc85f3420b3b37"
  license "MIT"

  depends_on :macos => :catalina # macOS 10.15
  depends_on :xcode => :build # Requires Xcode command line tools for swift build

  def install
    # Build both the library and the executable
    system "swift", "build", "-c", "release", "--disable-sandbox"

    # Install the executable
    bin.install ".build/release/CoreOCRCLI" => "coreocr"

    # Install the dynamic library
    lib.install ".build/release/libCoreOCRLib.dylib"
  end

  test do
    # A simple test that checks if the tool runs without crashing.
    # You might want to add a more specific test later.
    system "#{bin}/coreocr", "--version" # Assuming a --version flag exists or can be added
  end
end 