# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Coreocr < Formula
  desc "macOS CLI tool and Swift library for performing OCR using Vision"
  homepage "https://github.com/LESIM-Co-Ltd/CoreOCR"
  url "https://github.com/LESIM-Co-Ltd/CoreOCR/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "37812c685a2433165b72462ee866c2ac41eaa3e3874a7ebca9b2b864d811a48b"
  license "MIT"

  depends_on :macos => :catalina # macOS 10.15
  depends_on :xcode => :build # Requires Xcode command line tools for swift build

  def install
    system "swift", "build", "-c", "release", "--disable-sandbox"
    bin.install ".build/release/CoreOCRCLI" => "coreocr"
  end

  test do
    # A simple test that checks if the tool runs without crashing.
    # You might want to add a more specific test later.
    system "#{bin}/coreocr", "--version" # Assuming a --version flag exists or can be added
  end
end 